name: CI
on:
  push:
    branches:
    - master
    - 0.4.x
  pull_request:
    branches:
    - master
    - 0.4.x
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '21.0.0.java8'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: native-image
      run: |
        set -ex
        mkdir dist
        gu install native-image
        ./mvnw package -Pnative
        chmod +x target/classes/rsc*
        cp target/classes/rsc* ./rsc
        cp target/classes/rsc* ./dist/
        ./mvnw package -Dversion.generate.skip=true -DskipTests
        cp target/rsc*.jar ./dist/
        if [ -f ./dist/rsc-linux-x86_64 ];then
          mv ./dist/rsc-linux-x86_64 ./dist/rsc-x86_64-pc-linux
        fi
        if [ -f ./dist/rsc-osx-x86_64 ];then
          mv ./dist/rsc-osx-x86_64 ./dist/rsc-x86_64-apple-darwin
        fi
        ls -la ./dist
    - name: check-cli
      run: |
        set -ex
        env
        ./rsc --version
        ./rsc --showSystemProperties
        ./rsc ws://rsocket-demo.herokuapp.com/rsocket --route searchTweets --stream -d Trump --take 3 --retry 3 --debug
        ./rsc wss://rsocket-demo.herokuapp.com/rsocket --route searchTweets --stream -d Trump --take 3 --retry 3 --debug
    - name: upload-dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist